services:
  # GCS Mounter for KoboCAT bucket
  gcs-mounter-kobocat:
    image: ghcr.io/oucru-id/gcs-fuse:latest
    container_name: gcs-mounter-kobocat
    privileged: true
    restart: unless-stopped
    volumes:
      - ${SA_KEY_PATH}:/keys/sa-key.json:ro
      - ${KOBOCAT_BUCKET_PATH}:/mnt/gcs:shared
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/keys/sa-key.json
      - BUCKET_NAME=${KOBOCAT_BUCKET_NAME}
      - MOUNT_POINT=/mnt/gcs
      - GCSFUSE_UID=1000
      - GCSFUSE_GID=1000
      - FILE_MODE=777
      - DIR_MODE=777
      - ALLOW_OTHER=${ALLOW_OTHER}
      - IMPLICIT_DIRS=${IMPLICIT_DIRS}
    healthcheck:
      test: ["CMD", "mountpoint", "-q", "/mnt/gcs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - kobo-be-network

  # GCS Mounter for KPI bucket  
  gcs-mounter-kpi:
    image: ghcr.io/oucru-id/gcs-fuse:latest
    container_name: gcs-mounter-kpi
    privileged: true
    restart: unless-stopped
    volumes:
      - ${SA_KEY_PATH}:/keys/sa-key.json:ro
      - ${KPI_BUCKET_PATH}:/mnt/gcs:shared
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/keys/sa-key.json
      - BUCKET_NAME=${KPI_BUCKET_NAME}
      - MOUNT_POINT=/mnt/gcs
      - GCSFUSE_UID=1000
      - GCSFUSE_GID=1000
      - FILE_MODE=777
      - DIR_MODE=777
      - ALLOW_OTHER=${ALLOW_OTHER}
      - IMPLICIT_DIRS=${IMPLICIT_DIRS}
    healthcheck:
      test: ["CMD", "mountpoint", "-q", "/mnt/gcs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - kobo-be-network

networks:
  kobo-be-network: